### ISSUE TITLE
README entries that we need to update

### ISSUE THREAD

**Issue by mk-repos** [Lehao25/Stats506_public#1]
## ./Stats506_public/README.md

You have uploaded the problem set as well. I think you would be better to have a description of the problem set in the README.md file on the home page (`Lehao25/Stats506_public`) as well.

I know you just haven't updated it yet, but we need to add week4,5 group members and descriptions of the 4-5 activities as well.

**Comment by Lehao25** [comment]
Thanks. I update it now.
